Blog/Controllers/AdminController.cs
using Blog.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    [CustomLoginFilter]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Blog/Controllers/CikisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class CikisController : Controller
    {
        public ActionResult Index()
        {
            Session["giris"] = null;
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Controllers/KonuYonetimiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.DAL;
using Blog.Filters;

namespace Blog.Controllers
{
    [CustomLoginFilter]
    [RoutePrefix("admin")]
    public class KonuYonetimiController : Controller
    {
        private BlogEntities db = new BlogEntities();

        [Route("konu")]
        public ActionResult Index()
        {
            var konu = db.Konu.Include(k => k.Kategori).Include(k => k.Uye);
            return View(konu.ToList());
        }

        [Route("konu/detay/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konu konu = db.Konu.Find(id);
            if (konu == null)
            {
                return HttpNotFound();
            }
            return View(konu);
        }

        [Route("konu/yeni")]
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "Ad");
            ViewBag.UyeID = new SelectList(db.Uye, "ID", "EPosta");
            return View();
        }

        [Route("konu/yeni")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Baslik,Icerik,Tarih,OneCikar,UyeID,KategoriID,Resim")] Konu konu)
        {
            if (ModelState.IsValid)
            {
                konu.UyeID = ((Blog.DAL.Uye)Session["giris"]).ID;
                konu.Tarih = DateTime.Now;
                db.Konu.Add(konu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "Ad", konu.KategoriID);
            ViewBag.UyeID = new SelectList(db.Uye, "ID", "EPosta", konu.UyeID);
            return View(konu);
        }

        [Route("konu/duzenle/{id}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konu konu = db.Konu.Find(id);
            if (konu == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "Ad", konu.KategoriID);
            ViewBag.UyeID = new SelectList(db.Uye, "ID", "EPosta", konu.UyeID);
            return View(konu);
        }

        [Route("konu/duzenle/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Baslik,Icerik,Tarih,OneCikar,UyeID,KategoriID,Resim")] Konu konu)
        {
            if (ModelState.IsValid)
            {
                var yeni = db.Konu.Find(konu.ID);
                db.Konu.Attach(yeni);

                yeni.Baslik = konu.Baslik;
                yeni.Icerik = konu.Icerik;
                yeni.KategoriID = konu.KategoriID;
                yeni.Resim = konu.Resim;
                yeni.OneCikar = konu.OneCikar;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "Ad", konu.KategoriID);
            ViewBag.UyeID = new SelectList(db.Uye, "ID", "EPosta", konu.UyeID);
            return View(konu);
        }

        [Route("konu/sil/{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konu konu = db.Konu.Find(id);
            if (konu == null)
            {
                return HttpNotFound();
            }
            return View(konu);
        }

        [Route("konu/sil/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Konu konu = db.Konu.Find(id);
            db.Konu.Remove(konu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/UyeYonetimiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.DAL;
using Blog.Filters;

namespace Blog.Controllers
{
    [CustomLoginFilter]
    [RoutePrefix("admin")]
    public class UyeYonetimiController : Controller
    {
        private BlogEntities db = new BlogEntities();

        [Route("uye")]
        public ActionResult Index()
        {
            return View(db.Uye.ToList());
        }

        [Route("uye/detay/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        [Route("uye/yeni")]
        public ActionResult Create()
        {
            return View();
        }

        [Route("uye/yeni")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EPosta,Sifre,Ad,Soyad,Yetki")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Uye.Add(uye);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uye);
        }

        [Route("uye/duzenle/{id}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        [Route("uye/duzenle/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EPosta,Sifre,Ad,Soyad,Yetki")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uye);
        }

        [Route("uye/sil/{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        [Route("uye/sil/{id}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uye uye = db.Uye.Find(id);
            db.Uye.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Views/Shared/Genel.cshtml
@using Blog.Filters;
@{
    if (Session["giris"] != null)
    {
        var uye = (Blog.DAL.Uye)Session["giris"];
        ViewBag.UyeAd = uye.Ad;
    }
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Kişisel Blog</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <img src="~/Images/logo.png" class="logo" />
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Ana sayfa", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        <span class="sr-only">(current)</span>
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end">
                    @if (Session["giris"] == null)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Giriş", "Giris", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Kayıt Ol", "Kayit", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        var uye = (Blog.DAL.Uye)Session["giris"];
                        if (Yetki.Kontrol(uye.ID))
                        {
                        <li class="nav-item">
                            @Html.ActionLink("Yönetim Paneli", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hoşgeldin, @uye.Ad</a>
                            </li>
                        }
                        <li class="nav-item">
                            @Html.ActionLink("Çıkış", "Index", "Cikis", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
            <div class="col-md-4">

                <div class="col-md-12">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Aramak istediğinizi yazın..." aria-label="Aramak istediğinizi yazın..." aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-info" type="button" id="button-addon2">ARA</button>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 sidebar">
                    <div class="baslik">
                        <h4><i class="fas fa-align-justify"></i>Kategoriler</h4>
                    </div>
                    <div class="icerik">
                        <ul class="list-group">
                            @using (Blog.DAL.BlogEntities db = new Blog.DAL.BlogEntities())
                            {
                                foreach (var kategori in db.Kategori.ToList())
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        @Html.ActionLink(kategori.Ad, "KategoriKonuListele", new { id = kategori.ID })
                                        <span class="badge badge-primary badge-pill">@db.Konu.Count(h => h.KategoriID == kategori.ID).ToString()</span>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </div>

                <div class="col-md-12 sidebar">
                    <div class="baslik">
                        <h4><i class="fas fa-align-justify"></i>Arşiv</h4>
                    </div>
                    <div class="icerik arsiv">
                        <ul class="list-group">
                            @using (Blog.DAL.BlogEntities db = new Blog.DAL.BlogEntities())
                            {
                                foreach (var yil in db.Konu.Select(y => y.Tarih.Year).Distinct().ToList())
                                {
                                    <li class="list-group-item d-flex justify-content-between align-items-center yillar">
                                        @yil.ToString()
                                        <span class="badge badge-primary badge-pill">@db.Konu.Count(y => y.Tarih.Year == yil).ToString()</span>
                                    </li>

                                    foreach (var ay in db.Konu.Where(y => y.Tarih.Year == yil).Select(a => a.Tarih.Month).Distinct().ToList())
                                    {
                                        <li class="list-group-item d-flex justify-content-between align-items-center aylar">
                                            <a href="@Url.Action("TarihKonuListele", "Home", new { yil = yil, ay = ay} )">
                                                @switch (ay)
                                                {
                                                    case 1:
                                                        @ay.ToString("Ocak");
                                                        break;
                                                    case 2:
                                                        @ay.ToString("Şubat");
                                                        break;
                                                    case 3:
                                                        @ay.ToString("Mart");
                                                        break;
                                                    case 4:
                                                        @ay.ToString("Nisan");
                                                        break;
                                                    case 5:
                                                        @ay.ToString("Mayıs");
                                                        break;
                                                    case 6:
                                                        @ay.ToString("Haziran");
                                                        break;
                                                    case 7:
                                                        @ay.ToString("Temmuz");
                                                        break;
                                                    case 8:
                                                        @ay.ToString("Ağustos");
                                                        break;
                                                    case 9:
                                                        @ay.ToString("Eylül");
                                                        break;
                                                    case 10:
                                                        @ay.ToString("Ekim");
                                                        break;
                                                    case 11:
                                                        @ay.ToString("Kasım");
                                                        break;
                                                    case 12:
                                                        @ay.ToString("Aralık");
                                                        break;
                                                }
                                            </a>
                                            <span class="badge badge-primary badge-pill">@db.Konu.Count(k => k.Tarih.Year == yil && k.Tarih.Month == ay).ToString()</span>
                                        </li>
                                    }
                                }
                            }
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="footer">
            <div class="col-md-12">
                <div class="row justify-content-md-center">
                    <div class="col-md-4">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Ana sayfa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Kategoriler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Son Yazılar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Arşiv</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Arşiv</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Haberler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Yeniler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Haberler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Yeniler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-angle-double-right"></i>Haberler</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-facebook-square"></i>Facebook</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-twitter-square"></i>Twitter</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-instagram"></i>Instagram</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-pinterest-square"></i>Pinterest</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-google-plus-square"></i>Google+</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="row justify-content-md-center">
                        <div class="alt">
                            <p>Copyright &copy; @DateTime.Now.Year <a href="#">Site Adı</a> &copy; tüm hakları saklıdır.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Content/jquery-3.3.1.min.js"></script>
    <script src="~/Content/bootstrap.min.js"></script>
</body>
</html>

Blog/Views/Shared/Yonetim.cshtml
@{
    var uye = (Blog.DAL.Uye)Session["giris"];
    ViewBag.UyeAd = uye.Ad;
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Kişisel Blog</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <nav class="admin navbar navbar-expand-lg navbar-dark bg-dark">
            <img src="~/Images/logo.png" class="logo" />
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#genel" aria-controls="genel" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="genel">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Ana sayfa", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        <span class="sr-only">(current)</span>
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item">
                        @Html.ActionLink("Yönetim Paneli", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hoşgeldin, @ViewBag.UyeAd</a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Çıkış", "Index", "Cikis", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </nav>

        <nav class="admin-alt navbar navbar-expand-lg navbar-dark bg-secondary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#yonetim" aria-controls="yonetim" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="yonetim">
                <ul class="navbar-nav mr-auto justify-content-center">
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-dark dropdown-toggle" type="button" id="kategoriyonetimi" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Kategori Yönetimi
                            </button>
                            <div class="dropdown-menu" aria-labelledby="kategoriyonetimi">
                                @Html.ActionLink("Kategori Listesi", "Index", "KategoriYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Yeni Kategori Ekle", "Create", "KategoriYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-dark dropdown-toggle" type="button" id="uyeyonetimi" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Üye Yönetimi
                            </button>
                            <div class="dropdown-menu" aria-labelledby="uyeyonetimi">
                                @Html.ActionLink("Üye Listesi", "Index", "UyeYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Yeni Üye Ekle", "Create", "UyeYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-dark dropdown-toggle" type="button" id="konuyonetimi" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Konu Yönetimi
                            </button>
                            <div class="dropdown-menu" aria-labelledby="konuyonetimi">
                                @Html.ActionLink("Konu Listesi", "Index", "KonuYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Yeni Konu Ekle", "Create", "KonuYonetimi", new { @area = "" }, new { @class = "dropdown-item" })
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Content/jquery-3.3.1.min.js"></script>
    <script src="~/Content/bootstrap.min.js"></script>
</body>
</html>